name: Build server

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.9.0
      - name: Test server
        run: |
          npm install
          npm run lint
          npm run transpile:prod
          npm run coverage:silent
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          file: "./coverage/coverage-final.json"
          name: codecov
          fail_ci_if_error: true
