name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set tag version
        run: echo ::set-env name=TAG_VERSION::${GITHUB_REF#refs/*/}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Set current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - name: Install
        run: |
          npm ci
          npm run install:app
      - name: Build
        run: |
          npm run build:all -- --build-version ${{ env.TAG_VERSION }}
      - name: Zip
        run: |
          npm run zip:all -- --build-version ${{ env.TAG_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/porn-vault_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Discord notification
        env:
          DISCORD_USERNAME: GitHub
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Version **{{ EVENT_PAYLOAD.release.tag_name }}** released!! Link: *https://github.com/porn-vault/porn-vault/releases/tag/{{ EVENT_PAYLOAD.release.tag_name }}*"
